// Sales Dashboard — typed mock seed.
// Deterministic against MOCK_TODAY (2026-06-19) so KPIs, the funnel, and
// alerts render identically every load. Decoupled from Supabase entirely.
// At wire-up, replace these consts with createStore<T>().getAll() calls.

import type {
  Client,
  Deal,
  Lead,
  LeadMessage,
  LeadTask,
  PipelineStage,
} from "./types";

/** Sales owners. At wire-up these resolve from app_users. */
export interface Owner {
  id: string;
  name: string;
  initials: string;
}

export const OWNERS: Owner[] = [
  { id: "owner-ajay", name: "Ajay", initials: "AJ" },
  { id: "owner-dylan", name: "Dylan", initials: "DE" },
];

export const STAGES: PipelineStage[] = [
  { id: "stg-new", name: "New", position: 0, probability: 10, is_won: false, is_lost: false },
  { id: "stg-qualified", name: "Qualified", position: 1, probability: 25, is_won: false, is_lost: false },
  { id: "stg-call", name: "Call Booked", position: 2, probability: 40, is_won: false, is_lost: false },
  { id: "stg-discovery", name: "Discovery Done", position: 3, probability: 55, is_won: false, is_lost: false },
  { id: "stg-proposal", name: "Proposal Sent", position: 4, probability: 70, is_won: false, is_lost: false },
  { id: "stg-negotiation", name: "Negotiation", position: 5, probability: 85, is_won: false, is_lost: false },
  { id: "stg-won", name: "Closed Won", position: 6, probability: 100, is_won: true, is_lost: false },
  { id: "stg-lost", name: "Closed Lost", position: 7, probability: 0, is_won: false, is_lost: true },
];

// Helper to keep dates readable + relative to the frozen today (2026-06-19).
const d = (iso: string) => iso;

export const LEADS: Lead[] = [
  {
    id: "lead-pupford",
    name: "Hannah Pike",
    company: "Pupford",
    email: "hannah@pupford.com",
    phone: "+447700900111",
    source: "lander",
    revenue_band: "£500k–£1m",
    expected_mrr: 8000,
    owner_id: "owner-ajay",
    stage_id: "stg-negotiation",
    temperature: "hot",
    notes: "Wants Pro. Comparing us vs an in-house hire. Decision by month end.",
    last_contact_at: d("2026-06-18T14:00:00Z"),
    created_at: d("2026-05-20T09:00:00Z"),
    updated_at: d("2026-06-18T14:00:00Z"),
  },
  {
    id: "lead-verdant",
    name: "Marcus Reed",
    company: "Verdant Skincare",
    email: "marcus@verdant.co",
    phone: "+447700900222",
    source: "cal_com",
    revenue_band: "£1m–£3m",
    expected_mrr: 12000,
    owner_id: "owner-ajay",
    stage_id: "stg-proposal",
    temperature: "warm",
    notes: "Proposal sent for Pro. Procurement reviewing. Chase Friday.",
    last_contact_at: d("2026-06-16T10:30:00Z"),
    created_at: d("2026-05-28T11:00:00Z"),
    updated_at: d("2026-06-16T10:30:00Z"),
  },
  {
    id: "lead-northpeak",
    name: "Sofia Andersson",
    company: "NorthPeak Gear",
    email: "sofia@northpeak.io",
    phone: "+447700900333",
    source: "referral",
    revenue_band: "£3m+",
    expected_mrr: 12000,
    owner_id: "owner-dylan",
    stage_id: "stg-discovery",
    temperature: "hot",
    notes: "Referred by Verdant. Strong CRO appetite. Discovery went well.",
    last_contact_at: d("2026-06-17T16:00:00Z"),
    created_at: d("2026-06-02T09:00:00Z"),
    updated_at: d("2026-06-17T16:00:00Z"),
  },
  {
    id: "lead-lumen",
    name: "Tom Hayes",
    company: "Lumen Candles",
    email: "tom@lumencandles.com",
    phone: "+447700900444",
    source: "whatsapp",
    revenue_band: "£250k–£500k",
    expected_mrr: 8000,
    owner_id: "owner-ajay",
    stage_id: "stg-call",
    temperature: "warm",
    notes: "Booked a call after WhatsApp thread. Keen but budget-conscious.",
    last_contact_at: d("2026-06-15T12:00:00Z"),
    created_at: d("2026-06-08T15:00:00Z"),
    updated_at: d("2026-06-15T12:00:00Z"),
  },
  {
    id: "lead-fableknit",
    name: "Priya Nair",
    company: "FableKnit",
    email: "priya@fableknit.com",
    phone: "+447700900555",
    source: "instagram",
    revenue_band: "£250k–£500k",
    expected_mrr: 8000,
    owner_id: "owner-dylan",
    stage_id: "stg-qualified",
    temperature: "warm",
    notes: "DM'd via IG. Qualified on the lander follow-up. Needs a call booked.",
    last_contact_at: d("2026-06-14T09:00:00Z"),
    created_at: d("2026-06-10T10:00:00Z"),
    updated_at: d("2026-06-14T09:00:00Z"),
  },
  {
    id: "lead-saged",
    name: "Olivia Grant",
    company: "Saged Wellness",
    email: "olivia@saged.co",
    phone: "+447700900666",
    source: "lander",
    revenue_band: "£500k–£1m",
    expected_mrr: 8000,
    owner_id: "owner-ajay",
    stage_id: "stg-qualified",
    temperature: "cold",
    notes: "Went quiet after qualifying. No reply to last two emails.",
    last_contact_at: d("2026-06-11T08:00:00Z"),
    created_at: d("2026-06-04T12:00:00Z"),
    updated_at: d("2026-06-11T08:00:00Z"),
  },
  {
    id: "lead-orbit",
    name: "Daniel Cho",
    company: "Orbit Audio",
    email: "daniel@orbitaudio.com",
    phone: "+447700900777",
    source: "outbound",
    revenue_band: "£1m–£3m",
    expected_mrr: 12000,
    owner_id: "owner-dylan",
    stage_id: "stg-new",
    temperature: "nurture",
    notes: "Outbound reply. Interested for Q3, not now. Nurture.",
    last_contact_at: d("2026-06-12T13:00:00Z"),
    created_at: d("2026-06-12T13:00:00Z"),
    updated_at: d("2026-06-12T13:00:00Z"),
  },
  {
    id: "lead-brightbar",
    name: "Ella Moss",
    company: "BrightBar Nutrition",
    email: "ella@brightbar.com",
    phone: "+447700900888",
    source: "linkedin",
    revenue_band: "£500k–£1m",
    expected_mrr: 8000,
    owner_id: "owner-ajay",
    stage_id: "stg-new",
    temperature: "warm",
    notes: "LinkedIn DM (logged manually). Asked for case studies.",
    last_contact_at: d("2026-06-13T11:00:00Z"),
    created_at: d("2026-06-13T11:00:00Z"),
    updated_at: d("2026-06-13T11:00:00Z"),
  },
  {
    id: "lead-harbour",
    name: "James Whitlock",
    company: "Harbour & Hide",
    email: "james@harbourhide.com",
    phone: "+447700900999",
    source: "referral",
    revenue_band: "£1m–£3m",
    expected_mrr: 12000,
    owner_id: "owner-dylan",
    stage_id: "stg-proposal",
    temperature: "cold",
    notes: "Proposal sent 10 days ago, no movement. At risk.",
    last_contact_at: d("2026-06-09T10:00:00Z"),
    created_at: d("2026-05-25T09:00:00Z"),
    updated_at: d("2026-06-09T10:00:00Z"),
  },
  {
    id: "lead-mosswood",
    name: "Grace Bell",
    company: "Mosswood Home",
    email: "grace@mosswood.com",
    phone: "+447700901000",
    source: "lander",
    revenue_band: "£250k–£500k",
    expected_mrr: 8000,
    owner_id: "owner-ajay",
    stage_id: "stg-lost",
    temperature: null,
    notes: "Chose a freelancer. Price. Revisit in 6 months.",
    last_contact_at: d("2026-06-05T10:00:00Z"),
    created_at: d("2026-05-18T09:00:00Z"),
    updated_at: d("2026-06-06T10:00:00Z"),
  },
];

export const MESSAGES: LeadMessage[] = [
  // Pupford — active WhatsApp + email thread, one unread inbound
  {
    id: "msg-1",
    lead_id: "lead-pupford",
    channel: "email",
    direction: "inbound",
    subject: "Re: Conversion Engine proposal",
    body: "Thanks for sending this over. The Pro tier looks right. Can we talk contract length?",
    external_id: "gmail-aaa1",
    is_read: true,
    created_at: d("2026-06-17T09:00:00Z"),
  },
  {
    id: "msg-2",
    lead_id: "lead-pupford",
    channel: "email",
    direction: "outbound",
    subject: "Re: Conversion Engine proposal",
    body: "Of course. Standard is 6 months, but we can do 3 to start. Free Thursday for a quick call?",
    external_id: "gmail-aaa2",
    is_read: true,
    created_at: d("2026-06-17T11:30:00Z"),
  },
  {
    id: "msg-3",
    lead_id: "lead-pupford",
    channel: "whatsapp",
    direction: "inbound",
    subject: "",
    body: "Thursday 2pm works. Sending the team's questions before then 👍",
    external_id: "wa-bbb1",
    is_read: false,
    created_at: d("2026-06-18T14:00:00Z"),
  },
  // Verdant — proposal follow-up
  {
    id: "msg-4",
    lead_id: "lead-verdant",
    channel: "email",
    direction: "outbound",
    subject: "Conversion Engine — Pro proposal",
    body: "Attached is the Pro proposal with the projected uplift model. Happy to walk procurement through it.",
    external_id: "gmail-ccc1",
    is_read: true,
    created_at: d("2026-06-16T10:30:00Z"),
  },
  // FableKnit — IG DM unread
  {
    id: "msg-5",
    lead_id: "lead-fableknit",
    channel: "instagram",
    direction: "inbound",
    subject: "",
    body: "Loved the case study! What would onboarding look like for us?",
    external_id: "ig-ddd1",
    is_read: false,
    created_at: d("2026-06-14T09:00:00Z"),
  },
  // BrightBar — LinkedIn manual log
  {
    id: "msg-6",
    lead_id: "lead-brightbar",
    channel: "linkedin",
    direction: "inbound",
    subject: "",
    body: "[Logged manually] Saw your post on CRO for supplements — do you have results for nutrition brands?",
    external_id: null,
    is_read: true,
    created_at: d("2026-06-13T11:00:00Z"),
  },
  // Lumen — WhatsApp + cal.com
  {
    id: "msg-7",
    lead_id: "lead-lumen",
    channel: "cal_com",
    direction: "inbound",
    subject: "Discovery call booked",
    body: "Tom Hayes booked a 30-min discovery call for Jun 20, 3:00pm.",
    external_id: "cal-eee1",
    is_read: true,
    created_at: d("2026-06-15T12:00:00Z"),
  },
];

export const TASKS: LeadTask[] = [
  // Due today (2026-06-19)
  {
    id: "task-1",
    lead_id: "lead-verdant",
    title: "Chase procurement on proposal",
    due_at: d("2026-06-19T17:00:00Z"),
    completed_at: null,
    created_at: d("2026-06-16T10:30:00Z"),
  },
  // Overdue
  {
    id: "task-2",
    lead_id: "lead-saged",
    title: "Third follow-up email",
    due_at: d("2026-06-16T12:00:00Z"),
    completed_at: null,
    created_at: d("2026-06-11T08:00:00Z"),
  },
  // Future
  {
    id: "task-3",
    lead_id: "lead-pupford",
    title: "Send contract draft after Thursday call",
    due_at: d("2026-06-20T12:00:00Z"),
    completed_at: null,
    created_at: d("2026-06-18T14:00:00Z"),
  },
  // Completed
  {
    id: "task-4",
    lead_id: "lead-northpeak",
    title: "Send discovery recap",
    due_at: d("2026-06-18T12:00:00Z"),
    completed_at: d("2026-06-17T16:30:00Z"),
    created_at: d("2026-06-17T16:00:00Z"),
  },
];

// Two deals already closed this month → drive "MRR closing this month".
export const DEALS: Deal[] = [
  {
    id: "deal-1",
    lead_id: "lead-glasswing",
    plan: "core",
    mrr: 8000,
    setup_fee: 2000,
    contract_months: 6,
    closed_at: d("2026-06-04T10:00:00Z"),
    created_at: d("2026-06-04T10:00:00Z"),
  },
  {
    id: "deal-2",
    lead_id: "lead-tideline",
    plan: "pro",
    mrr: 12000,
    setup_fee: 3000,
    contract_months: 12,
    closed_at: d("2026-06-12T10:00:00Z"),
    created_at: d("2026-06-12T10:00:00Z"),
  },
];

// Clients created via the won-deal handoff (owner_id null = CSM unassigned).
export const CLIENTS: Client[] = [
  {
    id: "client-glasswing",
    name: "Glasswing Co",
    company: "Glasswing Co",
    lead_id: "lead-glasswing",
    pod_id: null,
    owner_id: null,
    plan: "core",
    mrr: 8000,
    status: "active",
    onboarded_at: d("2026-06-04T10:00:00Z"),
    renewal_date: d("2026-12-04T10:00:00Z"),
    created_at: d("2026-06-04T10:00:00Z"),
  },
  {
    id: "client-tideline",
    name: "Tideline Surf",
    company: "Tideline Surf",
    lead_id: "lead-tideline",
    pod_id: "pod-1",
    owner_id: "owner-dylan",
    plan: "pro",
    mrr: 12000,
    status: "active",
    onboarded_at: d("2026-06-12T10:00:00Z"),
    renewal_date: d("2027-06-12T10:00:00Z"),
    created_at: d("2026-06-12T10:00:00Z"),
  },
];
